[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

# Form notifications
[[plugins]]
  package = "@netlify/plugin-forms"

# Redirect rules for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Build optimization
[build.environment]
  NODE_VERSION = "18"

# Plugin for performance
[[plugins]]
  package = "@netlify/plugin-lighthouse"

# Compression and optimization
[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true

[build.processing.images]
  compress = true

